### PR TITLE
Added new filters with IDashboardAuthorizationFilter implementation

### PR DESCRIPTION
**Pull request by spoofi**
Since IAuthorizationFilter is obsolete:

1.  Nuget packages updated
2. Added new filters with implementation of IDashboardAuthorizationFilter (DashboardAuthorizationFilter, BasicDashboardAuthorizationFilter, ClaimsBasedDashboardAuthorizationFilter)
3. Readme updated

### CODE REVIEW

**Comment by lanierhall** [comment]
Is there a plan to merge this anytime soon?

**Comment by LanceMcCarthy** [comment]
Anyone have an example of this working? I'm still getting 401s after using the new filter class. I don't need any authentication at all, whats the best way to set this up (Azure deployed app service)?

image

**Comment by tynorton** [comment]
Without this PR, this project doesn't even work with latest HangFire.

**Comment by LanceMcCarthy** [comment]
After much finagling, here's what I had to do so it would work:

```
namespace MyNamespace
{
    public partial class Startup
    {
        public static void ConfigureMobileApp(IAppBuilder app)
        {
            var config = new HttpConfiguration();

            config.EnableSystemDiagnosticsTracing();

            new MobileAppConfiguration()
                .UseDefaultConfiguration()
                .ApplyTo(config);

            Database.SetInitializer(new ArtGalleryCRMInitializer());

            var settings = config.GetMobileAppSettingsProvider().GetMobileAppSettings();

            if (string.IsNullOrEmpty(settings.HostName))
            {
                app.UseAppServiceAuthentication(new AppServiceAuthenticationOptions
                {
                    SigningKey = ConfigurationManager.AppSettings["SigningKey"],
                    ValidAudiences = new[] { ConfigurationManager.AppSettings["ValidAudience"] },
                    ValidIssuers = new[] { ConfigurationManager.AppSettings["ValidIssuer"] },
                    TokenHandler = config.GetAppServiceTokenHandler()
                });
            }

            app.UseWebApi(config);
            
// ********** Here's where I initialize Hangfire ************ //
            InitializeHangFire(app);
        }
        
        private static void InitializeHangFire(IAppBuilder app)
        {
            GlobalConfiguration.Configuration.UseSqlServerStorage("MS_TableConnectionString");
            
            app.UseHangfireDashboard("/hangfire", new DashboardOptions
            {
                Authorization = new List<IDashboardAuthorizationFilter>
                {
                    new BasicDashboardAuthorizationFilter(new BasicAuthAuthorizationFilterOptions
                    {
                        RequireSsl = true,
                        LoginCaseSensitive = false,
                        Users = new[]
                        {
                            new BasicAuthAuthorizationUser
                            {
                                Login = "username",
                                PasswordClear = "password"
                            }
                        }
                    })
                }
            });

            app.UseHangfireServer();

            // Test - This job just edits the notes of one record with a timestamp so I can be assured it working
            RecurringJob.AddOrUpdate(() => new DatabaseHelpers().HeartbeatTestJob(), Cron.Hourly);

            // Database maintenance  options
            // RecurringJob.AddOrUpdate(() => new DatabaseHelpers().CleanDatabaseJob(), Cron.Daily);
            // RecurringJob.AddOrUpdate(() => new DatabaseHelpers().ResetDatabaseJob(), Cron.Weekly);
        }
    }
}
```

**Comment by mkwieci2** [comment]
Someone really needs to step in and merge this PR.

**Comment by stanislavromanov** [comment]
Can someone merge this? This package is useless without this PR.

**Comment by saitonakamura** [comment]
Since nobody of collaborators is answering and the last commit was in 2015, I suggest some of \you guys do a fork of this

**Comment by odinserj** [comment]
Thanks everyone for handling this and for your patience! :heart: I'm finally merging this PR and will release version 3.0.0 today, since it bumps Hangfire.Core dependency to 1.6.0, and this is a breaking change.

**Comment by odinserj** [comment]
Hm, not today – new classes aren't required (see aadbe4520f9a859a64209c3c48b8ac36f89023bf), and need to think about HMAC-based basic auth filter.

**Comment by odinserj** [comment]
Done – https://www.nuget.org/packages/Hangfire.Dashboard.Authorization/3.0.0 – thank you!

**Pull request merged**
