### PR TITLE
Added DashboardAuthorizationFilter

### PR DESCRIPTION
**Pull request by antonioseric**
Since AuthorizationFilter is obsolete

### CODE REVIEW

**Comment by mikanyg** [comment]
@odinserj when can we expect an update to the Hangfire.Dashboard.Authorization package?

**Comment by alexpantyukhin** [comment]
Also want to have reimplementation of `BasicAuthAuthorizationFilter`. I could do it if needed.

**Comment by kaldas** [comment]
@odinserj please can this be looked at?

**Comment by wakuflair** [comment]
The readme need update.

**Comment by odinserj** [comment]
Thank you @antonioseric, finally merging this PR :heart:

**Pull request merged**
